# Generated by Django 2.2.2 on 2019-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20190723_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='weeks_advice',
            field=models.BooleanField(default=False),
        ),
    ]
