# Generated by Django 2.2.2 on 2019-07-23 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0003_advice_weeks_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='passed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
