# Generated by Django 2.2.2 on 2019-07-24 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_advice_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='passed',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
