# Generated by Django 2.2.2 on 2019-07-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_auto_20190724_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
