# Generated by Django 2.2.2 on 2019-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_auto_20190724_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='media_type',
            field=models.CharField(default='image/png', max_length=50),
            preserve_default=False,
        ),
    ]
