# Generated by Django 2.2.2 on 2019-07-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_advice_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='media_type',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
