# Generated by Django 2.2.2 on 2019-07-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_auto_20190725_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='likes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
