# Generated by Django 2.2.2 on 2019-07-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_advice_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
