# Generated by Django 2.2.2 on 2019-08-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_auto_20190729_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='dislike',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(blank=True),
        ),
    ]
