# Generated by Django 2.2.2 on 2019-08-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_auto_20190815_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='dislike',
            field=models.BooleanField(null=True),
        ),
    ]
