# Generated by Django 2.2.2 on 2019-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0016_auto_20190815_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(null=True),
        ),
    ]
