# Generated by Django 2.2.2 on 2019-08-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0018_auto_20190815_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumthread',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='topic',
        ),
        migrations.DeleteModel(
            name='ForumAnswer',
        ),
        migrations.DeleteModel(
            name='ForumThread',
        ),
        migrations.DeleteModel(
            name='ForumTopic',
        ),
    ]
