# Generated by Django 2.2.2 on 2019-08-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0020_auto_20190819_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.TestQuestion'),
        ),
    ]
